name:                playground-haskell
version:             0.1.0.0
github:              "c089/playground-haskell"
license:             BSD3
author:              "Christoph Neuroth"
maintainer:          "christoph.neuroth@gmail.com"
copyright:           "2019 Christoph Neuroth"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/c089/playground-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  playground-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec == 2.6.1
    - playground-haskell
